# Official docker image.
image: docker:latest

# Use CI/CD group variables (Group Settings > CI/CD -> Variables)
variables:
  PUBLIC_IMAGE: $CI_PROJECT_NAME

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull --label org.opencontainers.image.revision=$CI_COMMIT_SHORT_SHA -t $PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    - tags

build-master:
  stage: build
  script:
    - docker build --pull -t "$PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:$CI_COMMIT_TAG" -t "$PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:latest" .
    - docker push "$PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:$CI_COMMIT_TAG"
    - docker push "$PUBLIC_REGISTRY/$PUBLIC_NAMESPACE/$PUBLIC_IMAGE:latest"
  only:
    - tags
